# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name { nativeBuildInputs = [ zig ]; } ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
      rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      ...
    }@args:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig (
          args
          // {
            url = "http://${path}";
          }
        );
        "git+https" = fetchGitZig (
          args
          // {
            url = "https://${path}";
          }
        );
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "ziggy-0.1.0-kTg8vwUbBgCFITTgm-mrp1_ypkLbd6nayrPtl2qpmrt_";
    path = fetchZigArtifact {
      name = "ziggy";
      url = "git+https://github.com/nihklas/ziggy#3aca019c37ea16fa6f59f8a1d6550b57e5c29818";
      hash = "sha256-/Na5VUo9UsvvevymmtPIpcLVdDxs9OBAfMkng0Ue9Ko=";
      rev = "3aca019c37ea16fa6f59f8a1d6550b57e5c29818";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
    path = fetchZigArtifact {
      name = "known_folders";
      url = "git+https://github.com/ziglibs/known-folders#aa24df42183ad415d10bc0a33e6238c437fc0f59";
      hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
      rev = "aa24df42183ad415d10bc0a33e6238c437fc0f59";
    };
  }
  {
    name = "lsp_kit-0.1.0-hAAxO8C9AADemCOc0CmRChs50IY82liZno5pFFN8HJs5";
    path = fetchZigArtifact {
      name = "lsp_kit";
      url = "git+https://github.com/nihklas/zig-lsp-kit#4e1d1b49261aea58e166a8d57382f32052584b74";
      hash = "sha256-6n3KPnxSPNfPxUyQ+9USKGWM8zr3K3CyxyQurvTPOtU=";
      rev = "4e1d1b49261aea58e166a8d57382f32052584b74";
    };
  }
  {
    name = "N-V-__8AABhrAQAQLLLGadghhPsdxTgBk9N9aLVOjXW3ay0V";
    path = fetchZigArtifact {
      name = "diffz";
      url = "https://github.com/ziglibs/diffz/archive/ef45c00d655e5e40faf35afbbde81a1fa5ed7ffb.tar.gz";
      hash = "sha256-Hdj0Z4Fxv9JHaqdHQ+SLzhCq0rkMLfA406xrDvN/w7o=";
    };
  }
  {
    name = "lsp_codegen-0.1.0-CMjjo0ZXCQB-rAhPYrlfzzpU0u0u2MeGvUucZ-_g32eg";
    path = fetchZigArtifact {
      name = "lsp_codegen";
      url = "git+https://github.com/zigtools/zig-lsp-codegen#063a98c13a2293d8654086140813bdd1de6501bc";
      hash = "sha256-KzRi/a3FCS11Mryin9skkf3rFrIuoMP8+RcU0IuYNBA=";
      rev = "063a98c13a2293d8654086140813bdd1de6501bc";
    };
  }
  {
    name = "zig_yaml-0.1.0-C1161hVrAgDsyB2EZnq-Vp-QuZ9xJm2y0dECRXGG3UaP";
    path = fetchZigArtifact {
      name = "yaml";
      url = "git+https://github.com/kubkon/zig-yaml#27f63d3d2d13ed228d8fc077635205e6c2a405c7";
      hash = "sha256-sDQHQ7uKDqAyvnEvfPheubn8C5QVWIXT9BdtT78UKeE=";
      rev = "27f63d3d2d13ed228d8fc077635205e6c2a405c7";
    };
  }
  {
    name = "zig_afl_kit-0.1.0-3k74fQAdAABrirJM84Lo-lnl9mnUMwtJCSPPyIJ0OzAr";
    path = fetchZigArtifact {
      name = "afl_kit";
      url = "git+https://github.com/nihklas/zig-afl-kit#676a439919c8ed736a84097f483d47d679f7e9df";
      hash = "sha256-wLHyZVjmUu6lNZBlGwuaX5XnKbEdMtov7YxJqn5IF3g=";
      rev = "676a439919c8ed736a84097f483d47d679f7e9df";
    };
  }
  {
    name = "AFLplusplus-4.21.0-aA1y4dFrAAB5IR-iHNHVO3lwlK3Blq2Xx-9I3vsxOKMF";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "git+https://github.com/allyourcodebase/AFLplusplus#bf7d9cc91a3897c3ed9a65b04141c87dded1bfe7";
      hash = "sha256-INL603zLnfPYIGgUaOQ0DQBwsRQJ6L7kG61D8YosuzI=";
      rev = "bf7d9cc91a3897c3ed9a65b04141c87dded1bfe7";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-EffHfTfP9uf2WsfMVbq3kB4MYgjoRaOHZDlNBO1WezA=";
    };
  }
  {
    name = "scripty-0.1.0-LKK5O8nDAADpuHWCt9Lar0LXr35wPjRS5a0BvopRdMYr";
    path = fetchZigArtifact {
      name = "scripty";
      url = "git+https://github.com/nihklas/scripty#1d7380fb61b7876823fd73962029888e0e41cc9d";
      hash = "sha256-p1uwNiyyWRQ2AHa3/tG870RJVZPgBt6s1yzNoxi4z+0=";
      rev = "1d7380fb61b7876823fd73962029888e0e41cc9d";
    };
  }
  {
    name = "tracy-0.0.0-4Xw-1pwwAABTfMgoDP1unCbZDZhJEfict7XCBGF6IdIn";
    path = fetchZigArtifact {
      name = "tracy";
      url = "git+https://github.com/kristoff-it/tracy#67d2d89e351048c76fc6d161e0ac09d8a831dc60";
      hash = "sha256-BKo1bhua/u+f5Z//ailur5aSHZWp3GiC0iwmVLrGZkE=";
      rev = "67d2d89e351048c76fc6d161e0ac09d8a831dc60";
    };
  }
  {
    name = "supermd-0.1.0-3Mco3AhtWAB-LGGevBAnTKZuYO5D4iXP8EBE61HN0mEc";
    path = fetchZigArtifact {
      name = "supermd";
      url = "git+https://github.com/nihklas/supermd#90a3a46a7b69217a7a6425a753e7c4e153cbb98f";
      hash = "sha256-nVSt3qjH4PrlshtZCuDN3cdjPMAXz6f8VU2X/qhMoGg=";
      rev = "90a3a46a7b69217a7a6425a753e7c4e153cbb98f";
    };
  }
  {
    name = "N-V-__8AAAyYFwBMxWQCepH-NgMp6xo8gVqjRQ1lMPQnzYG9";
    path = fetchZigArtifact {
      name = "gfm";
      url = "git+https://github.com/kristoff-it/cmark-gfm#675efb13f41f1dcaebfa0e9dc42d9b504e4b5508";
      hash = "sha256-BUcc06/zCzz42/wVcT5z45hsfcMXNog3wOOvFiuUdio=";
      rev = "675efb13f41f1dcaebfa0e9dc42d9b504e4b5508";
    };
  }
  {
    name = "superhtml-0.4.0-Y7MdPJCXDQB0zB9WVXeCJB7nh6Tw-wlgwDU9Se3IhDQD";
    path = fetchZigArtifact {
      name = "superhtml";
      url = "git+https://github.com/nihklas/superhtml#a976f30cecdf13bddadb5e96571ef55f19850556";
      hash = "sha256-A97xGaskZF0jXqzozhw5w+aZSPxx/PyE3ZKgYyduIi8=";
      rev = "a976f30cecdf13bddadb5e96571ef55f19850556";
    };
  }
  {
    name = "mime-2.0.1-AAAAAIQgAACQg7DEPQ9oompIp7Jq2fk7IsnP9xDHjd_r";
    path = fetchZigArtifact {
      name = "mime";
      url = "git+https://github.com/andrewrk/mime.git#0b676643886b1e2f19cf11b4e15b028768708342";
      hash = "sha256-FLNU5PI5O/e7RWhu4kn6wconLDPGyE4E2Bk/4ntG2FM=";
      rev = "0b676643886b1e2f19cf11b4e15b028768708342";
    };
  }
  {
    name = "zeit-0.0.0-AAAAALZOAgDpc1fMOfT58FPHY_PsFiPgx_OZnxhXRvK9";
    path = fetchZigArtifact {
      name = "zeit";
      url = "git+https://github.com/rockorager/zeit#52b100caa223d5cb1ff0d34f1b677f26e0ce8b84";
      hash = "sha256-cpWo2u7bpsNaNRGZTyjp9mCJOBt6s9G/p3biy5qdr0g=";
      rev = "52b100caa223d5cb1ff0d34f1b677f26e0ce8b84";
    };
  }
  {
    name = "flow_syntax-0.1.0-X8jOoUX-AADI9WdOuVSYK9yjyBOTFj4UicSapF7QQssd";
    path = fetchZigArtifact {
      name = "flow_syntax";
      url = "git+https://github.com/neurocyte/flow-syntax#d231728c92cb3c5a7139cb0d75a321a119b8e777";
      hash = "sha256-cvp/pf3HV3Frog5z6Uh6pIcTniH2fxg1e9e6tOVAL1c=";
      rev = "d231728c92cb3c5a7139cb0d75a321a119b8e777";
    };
  }
  {
    name = "N-V-__8AACablCbp-6lsRoKDEp6Xd2dHLe4AsW81blkSQxzs";
    path = fetchZigArtifact {
      name = "tree_sitter";
      url = "https://github.com/neurocyte/tree-sitter/releases/download/master-86dd4d2536f2748c5b4ea0e1e70678039a569aac/source.tar.gz";
      hash = "sha256-1AaipN8M3vvhj8ldPETYL3C6lyD7emUjw0F1yhx4CHM=";
    };
  }
  {
    name = "cbor-1.0.0-RcQE_HvqAACcrLH7t3IDZOshgY2xqJA_UX330MvwSepb";
    path = fetchZigArtifact {
      name = "cbor";
      url = "https://github.com/neurocyte/cbor/archive/1fccb83c70cd84e1dff57cc53f7db8fb99909a94.tar.gz";
      hash = "sha256-c0wlwa+jdqC2b2CfbLsb/l3vXVBnK7WkzUH7F49xqic=";
    };
  }
  {
    name = "wuffs-0.4.0-alpha.9+3837.20240914-3CHJgWsPAADpG9AWvKJ8ZxQ-t2IcnPEYVi_FD_o-qxjD";
    path = fetchZigArtifact {
      name = "wuffs";
      url = "git+https://github.com/allyourcodebase/wuffs#3646d8efae3f042ccbf552263ac6b2af738bdaa7";
      hash = "sha256-G0vZdfjW6CAcjOrwaujvvn9Gxw4VxIFi2wlwu2bRLT4=";
      rev = "3646d8efae3f042ccbf552263ac6b2af738bdaa7";
    };
  }
  {
    name = "N-V-__8AANEmUgA6aZZZKbfNMv6DSs5In7CDFU6nInu_Y6aY";
    path = fetchZigArtifact {
      name = "wuffs";
      url = "https://github.com/google/wuffs-mirror-release-c/archive/90e4d81a6a8b7b601e8e568da32a105d7f7705e5.tar.gz";
      hash = "sha256-3b68j7dAXnqRd+/fvfDfGK0CtgcxHZ5gSVnHwPYjavQ=";
    };
  }
  {
    name = "N-V-__8AALShqgXkvqYU6f__FrA22SMWmi2TXCJjNTO1m8XJ";
    path = fetchZigArtifact {
      name = "frameworks";
      url = "git+https://github.com/hexops/xcode-frameworks.git#8a1cfb373587ea4c9bb1468b7c986462d8d4e10e";
      hash = "sha256-b1Ay3GfBHwubnrGi4lflPiaqGfzWtABEbEiE8+ZTL90=";
      rev = "8a1cfb373587ea4c9bb1468b7c986462d8d4e10e";
    };
  }
]
